[tox]
envlist = py310, py311, py312, ruff, typing
skip_missing_interpreters = true
isolated_build = True

[testenv:py3]
basepython = python3

[testenv]
allowlist_externals =
    scripts/zhinst_qcodes_symlink.py
deps =
   py{310,311,312}: -rrequirements.txt
   pytest-cov
commands =
    # install toolkit first to ensure the correct version
    {envpython} -m pip install git+https://github.com/zhinst/zhinst-toolkit
    {envpython} -m pip install .
    {envpython} scripts/zhinst_qcodes_symlink.py
    {envpython} -m pytest --cov=zhinst.qcodes

[testenv:ruff]
deps =
    ruff
commands =
    ruff check .
    ruff format --check .

[testenv:typing]
deps =
    mypy
commands =
    mypy src
