"""Autogenerated module for the PQSC QCoDeS driver."""

from typing import Optional, Union

from zhinst.qcodes.driver.devices.base import ZIBaseInstrument
from zhinst.toolkit.driver.devices.base import BaseInstrument as TKBaseInstrument
from zhinst.toolkit.driver.devices.pqsc import PQSC as TKPQSC


class PQSC(ZIBaseInstrument):
    """QCoDeS driver for the Zurich Instruments PQSC."""

    _tk_object: TKPQSC

    def _init_additional_nodes(self):
        """Init class specific modules and parameters."""

    def run(self, *, deep: bool = True) -> None:
        """Start sending out triggers.

        This method activates the trigger generation to trigger all
        connected instruments over ZSync ports.

        Args:
            deep: A flag that specifies if a synchronization
                should be performed between the device and the data
                server after enabling the PQSC/QHub (default: True).

        """
        self._tk_object.run(deep=deep)

    def arm_and_run(
        self, *, repetitions: Optional[int] = None, holdoff: Optional[float] = None
    ) -> None:
        """Arm the PQSC/QHub and start sending out triggers.

        Simply combines the methods arm and run. A synchronization
        is performed between the device and the data server after
        arming and running the PQSC/QHub.

        Args:
            repetitions: If specified, the number of triggers sent
                over ZSync ports will be set (default: None).
            holdoff: If specified, the time between repeated
                triggers sent over ZSync ports will be set. It has a
                minimum value and a granularity of 100 ns
                (default: None).

        """
        self._tk_object.arm_and_run(repetitions=repetitions, holdoff=holdoff)

    def stop(self, *, deep: bool = True) -> None:
        """Stop the trigger generation.

        Args:
            deep: A flag that specifies if a synchronization
                should be performed between the device and the data
                server after disabling the PQSC/QHub (default: True).

        """
        self._tk_object.stop(deep=deep)

    def wait_done(self, *, timeout: float = 10.0, sleep_time: float = 0.005) -> None:
        """Wait until trigger generation and feedback processing is done.

        Args:
            timeout: The maximum waiting time in seconds for the
                PQSC/QHub (default: 10.0).
            sleep_time: Time in seconds to wait between
                requesting PQSC/QHub state

        Raises:
            TimeoutError: If the PQSC/QHub is not done sending out all
                triggers and processing feedback before the timeout.
        """
        self._tk_object.wait_done(timeout=timeout, sleep_time=sleep_time)

    def check_ref_clock(
        self, *, timeout: float = 30.0, sleep_time: float = 1.0
    ) -> bool:
        """Check if reference clock is locked successfully.

        Args:
            timeout: Maximum time in seconds the program waits
                (default: 30.0).
            sleep_time: Time in seconds to wait between
                requesting the reference clock status (default: 1)

        Raises:
            TimeoutError: If the process of locking to the reference clock
                exceeds the specified timeout.
        """
        return self._tk_object.check_ref_clock(timeout=timeout, sleep_time=sleep_time)

    def check_zsync_connection(
        self,
        inputs: Union[list[int], int, list[TKBaseInstrument], TKBaseInstrument],
        *,
        timeout: float = 10.0,
        sleep_time: float = 0.1,
    ) -> Union[list[bool], bool]:
        """Check if a ZSync connection is established.

        Checks the current status of the instrument connected to the given ports.
        If a instrument(s) is given instead of a port number, first finds the correct
        port number(s).

        Args:
            inputs: The port numbers to check the ZSync connection for.
                It can either be a single port number given as integer, a list
                of several port numbers an instrument or a list of instruments.
            timeout: Maximum time in seconds the program waits (default: 10.0).
            sleep_time: Time in seconds to wait between requesting the reference
                clock status (default: 0.1)

        Raises:
            TimeoutError: If the process of establishing a ZSync connection on
                one of the specified ports exceeds the specified timeout.
        """
        return self._tk_object.check_zsync_connection(
            inputs=inputs, timeout=timeout, sleep_time=sleep_time
        )

    def find_zsync_worker_port(
        self, device: TKBaseInstrument, timeout: float = 10.0, sleep_time: float = 0.1
    ) -> int:
        """Find the ID of the PQSC/QHub ZSync port connected to a given device.

        The function checks until the given timeout for the specified device to
        show up in the connection list.

        Args:
            device: device for which the connected ZSync port shall be found.
            timeout: Maximum time in seconds the program waits (default: 10.0).
            sleep_time: Time in seconds to wait between requesting the port
                serials list (default: 0.1)

        Returns:
            Index of the searched PQSC/QHub ZSync port.

        Raises:
            ToolkitError: If the given device doesn't appear to be connected
                to the PQSC/QHub via ZSync.
        """
        return self._tk_object.find_zsync_worker_port(
            device=device, timeout=timeout, sleep_time=sleep_time
        )

    def arm(
        self,
        *,
        deep: bool = True,
        repetitions: Optional[int] = None,
        holdoff: Optional[float] = None,
    ) -> None:
        """Prepare PQSC for triggering the instruments.

        This method configures the execution engine of the PQSC and
        clears the register bank. Optionally, the *number of triggers*
        and *hold-off time* can be set when specified as keyword
        arguments. If they are not specified, they are not changed.

        Note that the PQSC is disabled at the end of the hold-off time
        after sending out the last trigger. Therefore, the hold-off time
        should be long enough such that the PQSC is still enabled when
        the feedback arrives. Otherwise, the feedback cannot be processed.

        Args:
            deep: A flag that specifies if a synchronization
                should be performed between the device and the data
                server after stopping the PQSC and clearing the
                register bank (default: True).
            repetitions: If specified, the number of triggers sent
                over ZSync ports will be set (default: None).
            holdoff: If specified, the time between repeated
                triggers sent over ZSync ports will be set. It has a
                minimum value and a granularity of 100 ns
                (default: None).

        """
        self._tk_object.arm(deep=deep, repetitions=repetitions, holdoff=holdoff)
