"""Autogenerated module for the DataStreamingModule QCoDeS driver."""

import typing as t

from zhinst.qcodes.driver.modules.base_module import ZIBaseModule
from zhinst.toolkit.driver.modules.data_streaming_module import (
    DataStreamingModule as TKDataStreamingModule,
)

if t.TYPE_CHECKING:
    from zhinst.qcodes.session import Session


class ZIDataStreamingModule(ZIBaseModule):
    """Data Streaming Module.

    The Data Streaming Module provides functionality for continuous streaming of signals
    to the the API client and saving of data to file.
    The streamed signals are resampled onto a common sampling grid corresponding to that
    with the highest sampling rate. Linear interpolation is used for upsampling.
    The module provides a minimal interface - the duration of the capture is all that has
    to be specified, plus some extra parameters if saving to file is required.




    Args:
        tk_object: Underlying zhinst-toolkit object.
        session: Session to the Data Server.
        name: Name of the module in QCoDeS.
    """

    _tk_object: TKDataStreamingModule

    def __init__(
        self,
        tk_object: TKDataStreamingModule,
        session: "Session",
        name: str = "data_streaming_module",
    ):
        super().__init__(tk_object, session, name)

    def finish(self) -> None:
        """Stop the module."""
        self._tk_object.finish()

    def finished(self) -> bool:
        """Check if the acquisition has finished.

        Returns:
            Flag if the acquisition has finished.
        """
        return self._tk_object.finished()
