"""Autogenerated module for the TimelineModule QCoDeS driver."""

import typing as t

from zhinst.qcodes.driver.modules.base_module import ZIBaseModule
from zhinst.toolkit.driver.modules.timeline_module import (
    TimelineModule as TKTimelineModule,
)

if t.TYPE_CHECKING:
    from zhinst.qcodes.session import Session


class ZITimelineModule(ZIBaseModule):
    """Timeline Module.

    The Timeline Module enables users to create pulsed or timed experiments,
    including waveform generation, triggering and data acquisition.



    Args:
        tk_object: Underlying zhinst-toolkit object.
        session: Session to the Data Server.
        name: Name of the module in QCoDeS.
    """

    _tk_object: TKTimelineModule

    def __init__(
        self,
        tk_object: TKTimelineModule,
        session: "Session",
        name: str = "timeline_module",
    ):
        super().__init__(tk_object, session, name)

    def finish(self) -> None:
        """Stop the module."""
        self._tk_object.finish()

    def finished(self) -> bool:
        """Check if the timeline sequence has finished.

        Returns:
            True if the timeline sequence has finished.
        """
        return self._tk_object.finished()
